import { BASE_URL } from "../../shared/config/api.base.url.config";

export const API_URLS = {
    ACCESS_CODE_URL: BASE_URL + '/gbc/accesCode/',
    HISTO_CON_S_URL: BASE_URL + '/gbc/histoConS/',
    HISTO_ACTION_S_URL: BASE_URL + '/gbc/histoActionS/',
    AGENT_URL: BASE_URL + '/gbc/agents/',
    FOURNISSEUR_URL: BASE_URL + '/gbc/fournisseurs/',
    DIRECTION_SERVICE_URL: BASE_URL + '/gbc/directionService/',
    DESTINATAIRE_URL: BASE_URL + '/gbc/destinataires/',
    COMPTE_DESTINATAIRE_URL: BASE_URL + '/gbc/compteDestinataire/',
    AGENT_DIRECTION_SERVICE_DESTINATAIRE_VIEW_URL: BASE_URL + '/gbc/view/agentsDirectionServiceSDestinatairesView/',
    FOURNISSEURS_VIEW_URL: BASE_URL + '/gbc/view/fournisseurView/',
    ACCES_LIGNE_BUDGEATAIRE_URL: BASE_URL + '/gbc/accesLigneBudgetaire/',
    GRPE_CODE_URL: BASE_URL + '/gbc/grpeCode/',
    ACCES_CODE_NIVEAU_URL: BASE_URL + '/gbc/accesCodeNiveau/',
    BUDGET_URL: BASE_URL + '/gbc/budget/',
    GESTION_URL: BASE_URL + '/gbc/gestion/',
    BUDGET_TYPE_URL: BASE_URL + '/gbc/budgetType/',
    ACCES_LIGNE_BUDGETAIRE_NOMENCLATURED_BUDGET_URL: BASE_URL + '/gbc/view/accesLigneBudgetaireNomenclatureDBudgetView/',
    AGENT_ACCES_CODE_ACCES_CODE_NIVEAU_GRPE_CODE_URL: BASE_URL + '/gbc/view/agentAccesCodeAccesCodeNiveauGrpeCodeView/',
    BUDGET_NOMENCLATURED_VIEW_URL: BASE_URL + '/gbc/view/budgetNomenclaturedView/',
    PJ_URL: BASE_URL + '/gbc/pj/',
    NOMENCLATURED_URL: BASE_URL + '/gbc/nomenclatured/',
    PLAN_COMPTABLE_URL: BASE_URL + '/gbc/planComptable/',
    INSTITUT_FINANCIER_URL: BASE_URL + '/gbc/institutFinancier/',
    INSTITUT_FIN_AGENCE_URL: BASE_URL + '/gbc/institutFinAgence/',
    RETENUE_CATEGORIE_URL: BASE_URL + '/gbc/retenueCategorie/',
    RETENU_TYPE_URL: BASE_URL + '/gbc/retenuType/',
    COMPTE_URL: BASE_URL + '/gbc/compte/',
    COUPURE_MONNAIE_URL: BASE_URL + '/gbc/coupureMonnaie/',
    ENTETE_STRUCUTRE_URL: BASE_URL + '/gbc/enteteStructure/',
    ENTETE_URL: BASE_URL + '/gbc/entete/',
    DIRECTION_SERVICE_NIVEAU_URL: BASE_URL + '/gbc/directionServiceNiveau/',
    DECISION_SVISA_URL: BASE_URL + '/gbc/decisionSVisa/',
    DECISION_SARTICLE_URL: BASE_URL + '/gbc/decisionSArticle/',
    DECISION_SAMPLIATION_URL: BASE_URL + '/gbc/decisionSAmpliation/',
    TYPE_DECISION_URL: BASE_URL + '/gbc/typeDecision/',
    ST_ELEMENTS_URL: BASE_URL + '/gbc/stElements/',
    ST_ELEMENTS_NOMENCLA_URL: BASE_URL + '/gbc/stElementsNomencla/',
    RECETTES_POUR_MAJ_BUDGET_VIEW_URL: BASE_URL + '/gbc/view/recettesPourMajBudgetView/',
    DEPENSES_POUR_MAJ_BUDGET_VIEW_URL: BASE_URL + '/gbc/view/depensesPourMajBudgetView/',
    BUDGET_MODIF_ACTE_URL: BASE_URL + '/gbc/budgetModifActe/',
    BUDGET_MODIF_URL: BASE_URL + '/gbc/budgetModif/',
    LIGNES_MODIFIESS_RECETTES_POUR_VALIDATION_MODIFICATION_BUDGET_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesRecettesPourValidationModificationBudgetView/',
    LIGNES_MODIFIESS_DEPENSES_POUR_VALIDATION_MODIFICATION_BUDGET_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesDepensesPourValidationModificationBudgetView/',
    LIGNES_MODIFIESS_RECETTES_POUR_ANNULER_VALIDATION_MODIFICATION_BUDGET_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesRecettesPourAnnulerValidationModificationBudgetView/',
    LIGNES_MODIFIESS_DEPENSES_POUR_ANNULER_VALIDATION_MODIFICATION_BUDGET_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesDepensesPourAnnulerValidationModificationBudgetView/',
    RECETTES_POUR_REAMENAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/recettesPourReamenagementView/',
    DEPENSES_POUR_REAMENAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/depensesPourReamenagementView/',
    REAMGMT_URL: BASE_URL + '/gbc/reamgmt/',
    REAMGMT_ACTE_URL: BASE_URL + '/gbc/reamgmtActe/',
    ACTE_NATURE_URL: BASE_URL + '/gbc/acteNature/',
    LIGNES_MODIFIESS_RECETTES_POUR_VALIDATION_REAMENAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesRecettesPourValidationReamenagementView/',
    LIGNES_MODIFIESS_DEPENSES_POUR_VALIDATION_REAMENAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesDepensesPourValidationReamenagementView/',
    LIGNES_MODIFIESS_RECETTES_POUR_ANNULER_VALIDATION_REAMENAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesRecettesPourAnnulerValidationReamenagementView/',
    LIGNES_MODIFIESS_DEPENSES_POUR_ANNULER_VALIDATION_REAMENAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/lignesModifieesDepensesPourAnnulerValidationReamenagementView/',
    
    CONTRAT_TYPE_URL: BASE_URL + '/gbc/contratType/',

    LIQUIDATIONS_POUR_CREATION_ENGAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/liquidationsPourCreationEngagementView/',
    DEPENSES_POUR_CREATION_ENGAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/depensesPourCreationEngagementView/',
    CONTRATS_POUR_CREATION_ENGAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/contratsPourCreationEngagementView/',
    CONTRATS_VIEW_URL: BASE_URL + '/gbc/view/contratsView/',
    PIECE_JUSTIF_URL: BASE_URL + '/gbc/pieceJustif/',
    ENGAGEMENT_URL: BASE_URL + '/gbc/engagements/',
    MANDAT_URL: BASE_URL + '/gbc/mandats/',
    ENGAGEMENT_VIEW_URL: BASE_URL + '/gbc/view/engagementView/',
    ENGAGEMENT_EN01_VIEW_URL: BASE_URL + '/gbc/view/engagementEN01View/',
    ENGAGEMENT_EN02_VIEW_URL: BASE_URL + '/gbc/view/engagementEN02View/',
    BORD_TRANSMIS_URL: BASE_URL + '/gbc/bordTransmis/',
    BORD_TRANSMIS_VIEW_URL: BASE_URL + '/gbc/view/bordTransmisView/',
    MOTIFS_REJET_DOSSIER_URL: BASE_URL + '/gbc/motifsRejetDossier/',
    LIQUIDATION_URL: BASE_URL + '/gbc/liquidation/',
    
    LIQUIDATION_VIEW_URL: BASE_URL + '/gbc/view/liquidationView/',

    MANDATS_VIEW_URL: BASE_URL + '/gbc/view/mandatsView/',
    BORDEREAU_EMIS_MANDATS_URL: BASE_URL + '/gbc/bordereauEmismandats/',
    BORDEREAU_EMIS_MANDATS_VIEW_URL: BASE_URL + '/gbc/view/bordereauEmismandatsView/',
    BORD_MAND_URL: BASE_URL + '/gbc/bordMand/',

    COD_ENTITE_CONTRACT_URL: BASE_URL + '/gbc/codEntiteContract/',
    COD_NAT_CONTRAT_URL: BASE_URL + '/gbc/codNatContrat/',
    COD_MOD_PASS_URL: BASE_URL + '/gbc/codModPass/',
    TYPE_MARCHE_URL: BASE_URL + '/gbc/typeMarche/',
    IDENTITE_EXECUTION_URL: BASE_URL + '/gbc/identiteExecution/',
    PPM_EXEC_BUDG_VIEW_URL: BASE_URL + '/gbc/view/ppmExecBudgView/',
    CONTRATS_URL: BASE_URL + '/gbc/contrats/',

    // uAristide
    PPM_URL: BASE_URL + `/gbc/ppm/`,
    PPM_MOD_PASS_URL: BASE_URL + `/gbc/ppmModPass/` ,
    PPM_BUDG_URL: BASE_URL + `/gbc/ppmBudg/` , 
    PPM_ACTE_URL: BASE_URL + `/gbc/ppmActe/` ,
    CODE_SOURCE_FIN_GET_URL: BASE_URL + '/gbc/codSourceFin/',
    DEPENSES_POUR_PPM_BUDGET_VIEW: BASE_URL + `/gbc/view/DepensesPourPpmBudgetView/`,
    DEPENSES_LIGNES_BUDGETAIRE_EN_FONCTION_DE_PPM_VIEW: BASE_URL + `/gbc/view/depensesLignesBudgetaireEnFonctionDePpmView/`,
    PPM_DAC_URL: BASE_URL + `/gbc/ppmDac/` ,
    PPM_EXEC_URL: BASE_URL + `/gbc/ppmExec/`,
    PPM_EXEC_BUDG_URL: BASE_URL + `/gbc/ppmExecBudg/`
}