export interface AgentsDirectionServiceSDestinatairesViewDto {
	mle: any,
	nom: any,
	prenom: any,
	sexe: any,
	signataire: any,
	titreHonoSign: any,
	actif: any,
	idService: any,
	libelle: any,
	abrev: any,
	idHerachique: any,
	idNiveau: any,
	codStruct: any,
	idParent: any,
	ifumle: any,
	ftype: any,
	contactTel: any,
	contactEmail: any,
}