export interface BudgetNomenclaturedViewDto {
	codBud: any,
	intitule: any,
	dotInitiale: any,
	caajout: any,
	caannul: any,
	ream: any,
	totalEngag: any,
	gestion: any,
	numNo: any,
	idBudget: any,
	idPlan: any,
	titre: any,
	section: any,
	chap: any,
	art: any,
	parag: any,
	rub: any,
	dotEstExec: any,
	codHierarchiq: any,
}