export interface LiquidationsPourCreationEngagementViewDto {
	codLiq: any,
	gestion: any,
	numBl: any,
	dateLiq: any,
	objet: any,
	montant: any,
	montEngage: any,
	montDjaLiq: any,
	modifiable: any,
	idUser: any,
	numeroDemande: any,
	dateModif: any,
	actif: any,
	idBudget: any,
	compteFourn: any,
	idContrat: any,
	numBe: any,
	idFourn: any,
	ifumle: any,
	ftype: any,
	contactTel: any,
	contactEmail: any,
	nom: any,
}