export interface MandatRequestDto {
	dateMand: any;
	montant: any;
	dateEtat: any;
	datePaie: any;
	montantPaie: any;
	idCompte: any;
	idUser: any;
	datePosition: any;
	benum: any;
	objet: any;
	montEngage: any;
	montDjaLiq: any;
	dateEtatBl: any;
	datePec: any;
	receptionne: any;
	genererOv: any;
	avecReversement: any;
	precompte: any;
	datePrecompte: any;
	userPrecompte: any;
	dateValid: any;
	idFiche: any;
	montantTotalPec: any;
	dateCreat: any;
	estOrdre: any;
	mandNumApresVisaCf: any;
	idEtatTransL: any;
	idEtatTransM: any;
	idBordEmis: any;
	idBord: any;
	codBud: any;
	idBudget: any;
	compteFourn: any;
	idContrat: any;
	idFourn: any;
	gestion: any;
	codLiq: any;
	idLettrage: any;
	idModePaie: any;
	numBe: any;
	etat: any;
	etatBl: any;
	numMandParent: any;
}

export const emptyMandatRequestDto: MandatRequestDto = {
	dateMand: null,
	montant: null,
	dateEtat: null,
	datePaie: null,
	montantPaie: null,
	idCompte: null,
	idUser: null,
	datePosition: null,
	benum: null,
	objet: null,
	montEngage: null,
	montDjaLiq: null,
	dateEtatBl: null,
	datePec: null,
	receptionne: null,
	genererOv: null,
	avecReversement: null,
	precompte: null,
	datePrecompte: null,
	userPrecompte: null,
	dateValid: null,
	idFiche: null,
	montantTotalPec: null,
	dateCreat: null,
	estOrdre: null,
	mandNumApresVisaCf: null,
	idEtatTransL: null,
	idEtatTransM: null,
	idBordEmis: null,
	idBord: null,
	codBud: null,
	idBudget: null,
	compteFourn: null,
	idContrat: null,
	idFourn: null,
	gestion: null,
	codLiq: null,
	idLettrage: null,
	idModePaie: null,
	numBe: null,
	etat: null,
	etatBl: null,
	numMandParent: null,
}

export interface MandatResponseDto {
	numMand: any;
	mandNum: any;
	dateMand: any;
	montant: any;
	dateEtat: any;
	datePaie: any;
	montantPaie: any;
	idCompte: any;
	idUser: any;
	datePosition: any;
	benum: any;
	numBl: any;
	objet: any;
	montEngage: any;
	montDjaLiq: any;
	dateEtatBl: any;
	datePec: any;
	receptionne: any;
	genererOv: any;
	avecReversement: any;
	precompte: any;
	datePrecompte: any;
	userPrecompte: any;
	dateValid: any;
	idFiche: any;
	montantTotalPec: any;
	dateCreat: any;
	estOrdre: any;
	mandNumApresVisaCf: any;
	idEtatTransL: any;
	idEtatTransM: any;
	idBordEmis: any;
	idBord: any;
	codBud: any;
	idBudget: any;
	compteFourn: any;
	idContrat: any;
	idFourn: any;
	gestion: any;
	codLiq: any;
	idLettrage: any;
	idModePaie: any;
	numBe: any;
	etat: any;
	etatBl: any;
	numMandParent: any;
	codBordsBordTransMand: any;
	codBordsBordTransLiq: any;
	idRetenusQuitOrdres: any;
	idMandatsCloture: any;
	pieceJustifComplemenIds: any;
	idCompteMouvementMandRs: any;
	idRetenuTitreRecouvs: any;
	idMandLettragPaies: any;
	chequesVirementsIds: any;
	codRecouvs: any;
	numMands: any;
	idPieceJournalsForNumMand: any;
	idPieceJournalsForIdMandRetenu: any;
	idJustifs: any;
	mandatPecIds: any;
	bordMandIds: any;
	idRetenus: any;
}

export const emptyMandatResponseDto: MandatResponseDto = {
	numMand: null,
	mandNum: null,
	dateMand: null,
	montant: null,
	dateEtat: null,
	datePaie: null,
	montantPaie: null,
	idCompte: null,
	idUser: null,
	datePosition: null,
	benum: null,
	numBl: null,
	objet: null,
	montEngage: null,
	montDjaLiq: null,
	dateEtatBl: null,
	datePec: null,
	receptionne: null,
	genererOv: null,
	avecReversement: null,
	precompte: null,
	datePrecompte: null,
	userPrecompte: null,
	dateValid: null,
	idFiche: null,
	montantTotalPec: null,
	dateCreat: null,
	estOrdre: null,
	mandNumApresVisaCf: null,
	idEtatTransL: null,
	idEtatTransM: null,
	idBordEmis: null,
	idBord: null,
	codBud: null,
	idBudget: null,
	compteFourn: null,
	idContrat: null,
	idFourn: null,
	gestion: null,
	codLiq: null,
	idLettrage: null,
	idModePaie: null,
	numBe: null,
	etat: null,
	etatBl: null,
	numMandParent: null,
	codBordsBordTransMand: null,
	codBordsBordTransLiq: null,
	idRetenusQuitOrdres: null,
	idMandatsCloture: null,
	pieceJustifComplemenIds: null,
	idCompteMouvementMandRs: null,
	idRetenuTitreRecouvs: null,
	idMandLettragPaies: null,
	chequesVirementsIds: null,
	codRecouvs: null,
	numMands: null,
	idPieceJournalsForNumMand: null,
	idPieceJournalsForIdMandRetenu: null,
	idJustifs: null,
	mandatPecIds: null,
	bordMandIds: null,
	idRetenus: null,
}