//Aristide
export interface ppmActeRequestDto {
     idPpmM:any,
	 gestion ?:any,
	 quantieme ?:any,
	 dateModif ?:any,
	 motifModif ?:any,
	 acteAutorisation ?:any,
	 dateCreate ?:any,
	 userCreate ?:any,
	 dateUpdate ?:any,
	 userUpdate ?:any,
	 valide:any,
	 userValide ?:any,
	 dateValide ?:any,
	 idPpmMMP ?:any,
	 idBudget ?:any,
}

export const emptyPpmActeRequestDto :ppmActeRequestDto = {
     idPpmM:null,
	 gestion:null,
	 quantieme:null,
	 dateModif:null,
	 motifModif:null,
	 acteAutorisation:null,
	 dateCreate:null,
	 userCreate:null,
	 dateUpdate:null,
	 userUpdate:null,
	 valide:null,
	 userValide:null,
	 dateValide:null,
	 idPpmMMP:null,
	 idBudget:null,
}

export interface ppmActeResponseDto {
    idPpmM:any,
	 gestion:any,
	 quantieme:any,
	 dateModif:any,
	 motifModif:any,
	 acteAutorisation:any,
	 dateCreate:any,
	 userCreate:any,
	 dateUpdate:any,
	 userUpdate:any,
	 valide:any,
	 userValide:any,
	 dateValide:any,
	 idPpmMMP:any,
	 idBudget:any,
     ppmOldIds:any,
	 ppmBudgOldIds:any
	 idPpmMs:any,
	 idPpms: any,
	 
}

export const emptyPpmActeResponseDto : ppmActeResponseDto ={
    idPpmM:null,
	gestion:null,
	quantieme:null,
	dateModif:null,
	motifModif:null,
	acteAutorisation:null,
	dateCreate:null,
	userCreate:null,
	dateUpdate:null,
	userUpdate:null,
	valide:null,
	userValide:null,
	dateValide:null,
	idPpmMMP:null,
	idBudget:null,
    ppmOldIds:null,
	ppmBudgOldIds:null,
	idPpmMs:null,
	idPpms: null,
}