export interface EnteteStructureRequestDto {
	abrevEpe: any;
	section: any;
	epe: any;
	lieu: any;
	logo: any;
	signataireDg: any;
	nomSignataireDg: any;
	titreHonorifiqueDg: any;
	signataireDaf: any;
	nomSignataireDaf: any;
	titreHonorifiqueDaf: any;
	signataireCf: any;
	nomSignataireCf: any;
	titreHonorifiqueCf: any;
	signataireAc: any;
	nomSignataireAc: any;
	titreHonorifiqueAc: any;
	cfresident: any;
	signatPenal: any;
	adresse: any;
	telephone: any;
	fax: any;
	email: any;
	visa: any;
	articleStruct: any;
	nomPays: any;
	devisePays: any;
	mleCnss: any;
	mleCarfo: any;
	typeSupport: any;
	avecReception: any;
	quitFiligrane: any;
	tauxTva: any;
	typeAmmortDefaut: any;
	gbc: any;
	gim: any;
	grh: any;
	sectionNum: any;
	filgraneL276cmH185cm: any;
	signataireDrh: any;
	nomSignataireDrh: any;
	titreHonorifiqueDrh: any;
	idCircuitGrh: any;
	drhsigneEtat: any;
	libAnnee: any;
	mandNumApresVisaCf: any;
}

export const emptyEnteteStructureRequestDto: EnteteStructureRequestDto = {
	abrevEpe: null,
	section: null,
	epe: null,
	lieu: null,
	logo: null,
	signataireDg: null,
	nomSignataireDg: null,
	titreHonorifiqueDg: null,
	signataireDaf: null,
	nomSignataireDaf: null,
	titreHonorifiqueDaf: null,
	signataireCf: null,
	nomSignataireCf: null,
	titreHonorifiqueCf: null,
	signataireAc: null,
	nomSignataireAc: null,
	titreHonorifiqueAc: null,
	cfresident: null,
	signatPenal: null,
	adresse: null,
	telephone: null,
	fax: null,
	email: null,
	visa: null,
	articleStruct: null,
	nomPays: null,
	devisePays: null,
	mleCnss: null,
	mleCarfo: null,
	typeSupport: null,
	avecReception: null,
	quitFiligrane: null,
	tauxTva: null,
	typeAmmortDefaut: null,
	gbc: null,
	gim: null,
	grh: null,
	sectionNum: null,
	filgraneL276cmH185cm: null,
	signataireDrh: null,
	nomSignataireDrh: null,
	titreHonorifiqueDrh: null,
	idCircuitGrh: null,
	drhsigneEtat: null,
	libAnnee: null,
	mandNumApresVisaCf: null,
}

export interface EnteteStructureResponseDto {
	abrevEpe: any;
	section: any;
	epe: any;
	lieu: any;
	logo: any;
	signataireDg: any;
	nomSignataireDg: any;
	titreHonorifiqueDg: any;
	signataireDaf: any;
	nomSignataireDaf: any;
	titreHonorifiqueDaf: any;
	signataireCf: any;
	nomSignataireCf: any;
	titreHonorifiqueCf: any;
	signataireAc: any;
	nomSignataireAc: any;
	titreHonorifiqueAc: any;
	cfresident: any;
	signatPenal: any;
	adresse: any;
	telephone: any;
	fax: any;
	email: any;
	visa: any;
	articleStruct: any;
	nomPays: any;
	devisePays: any;
	mleCnss: any;
	mleCarfo: any;
	typeSupport: any;
	avecReception: any;
	quitFiligrane: any;
	tauxTva: any;
	typeAmmortDefaut: any;
	gbc: any;
	gim: any;
	grh: any;
	sectionNum: any;
	filgraneL276cmH185cm: any;
	signataireDrh: any;
	nomSignataireDrh: any;
	titreHonorifiqueDrh: any;
	idCircuitGrh: any;
	drhsigneEtat: any;
	libAnnee: any;
	mandNumApresVisaCf: any;
	enteteCodUsers: any;
}

export const emptyEnteteStructureResponseDto: EnteteStructureResponseDto = {
	abrevEpe: null,
	section: null,
	epe: null,
	lieu: null,
	logo: null,
	signataireDg: null,
	nomSignataireDg: null,
	titreHonorifiqueDg: null,
	signataireDaf: null,
	nomSignataireDaf: null,
	titreHonorifiqueDaf: null,
	signataireCf: null,
	nomSignataireCf: null,
	titreHonorifiqueCf: null,
	signataireAc: null,
	nomSignataireAc: null,
	titreHonorifiqueAc: null,
	cfresident: null,
	signatPenal: null,
	adresse: null,
	telephone: null,
	fax: null,
	email: null,
	visa: null,
	articleStruct: null,
	nomPays: null,
	devisePays: null,
	mleCnss: null,
	mleCarfo: null,
	typeSupport: null,
	avecReception: null,
	quitFiligrane: null,
	tauxTva: null,
	typeAmmortDefaut: null,
	gbc: null,
	gim: null,
	grh: null,
	sectionNum: null,
	filgraneL276cmH185cm: null,
	signataireDrh: null,
	nomSignataireDrh: null,
	titreHonorifiqueDrh: null,
	idCircuitGrh: null,
	drhsigneEtat: null,
	libAnnee: null,
	mandNumApresVisaCf: null,
	enteteCodUsers: null
}